[[libserialport]]
arch = "armv7l"
git-tree-sha1 = "ae50140dab864240ca072379b91652b56fe24f62"
libc = "musl"
os = "linux"

    [[libserialport.download]]
    sha256 = "806ee4edbcd9a98236592dba8ca91304d19a8b530c4f9295532b71efd4e7458a"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.arm-linux-musleabihf.tar.gz"
[[libserialport]]
arch = "powerpc64le"
git-tree-sha1 = "9577754f9d53535da2e4f8d4916003396a3b8f8a"
libc = "glibc"
os = "linux"

    [[libserialport.download]]
    sha256 = "53d267180a4da7a2fe3b952222c835826eafea74ca0269f994df7aee40d6875b"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[libserialport]]
arch = "x86_64"
git-tree-sha1 = "4333bf5d4811660aa447e6e461b9a28f3eaa4d9e"
os = "macos"

    [[libserialport.download]]
    sha256 = "403513a685751996f4737f996434150f4fa2cf144e6c8795a9d6501407d31b15"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.x86_64-apple-darwin14.tar.gz"
[[libserialport]]
arch = "aarch64"
git-tree-sha1 = "0ed033b81002ba187443174ced986f6b5bed402b"
libc = "glibc"
os = "linux"

    [[libserialport.download]]
    sha256 = "3c32dbc59d75d8bd7f937b510575cf4cd7b555bd5e54822997d998a13097f26e"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.aarch64-linux-gnu.tar.gz"
[[libserialport]]
arch = "armv7l"
git-tree-sha1 = "8d8a5300bef521307dcf36fe5ea13956585cd4e6"
libc = "glibc"
os = "linux"

    [[libserialport.download]]
    sha256 = "c4db866222b2c7d17277fea0cb5363cf0628379307b9a4dd7dac344599d1245f"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.arm-linux-gnueabihf.tar.gz"
[[libserialport]]
arch = "i686"
git-tree-sha1 = "261b4016c6a3b0440734cfc011d28b0d2f6db113"
libc = "musl"
os = "linux"

    [[libserialport.download]]
    sha256 = "637485a10be708ff85bce018757fa592ae5ef4cd95d43bfd5b3934dac5b4e544"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.i686-linux-musl.tar.gz"
[[libserialport]]
arch = "x86_64"
git-tree-sha1 = "939cdd32e306775f4c57d49341082a747bb8b561"
libc = "glibc"
os = "linux"

    [[libserialport.download]]
    sha256 = "7ed4f6fdbc7187931dc39a893efedd7a6310c4c0cdba87e18163fc52931333be"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.x86_64-linux-gnu.tar.gz"
[[libserialport]]
arch = "x86_64"
git-tree-sha1 = "d274ac7b4181fe68a3754d2b3f90252cb86f895a"
os = "windows"

    [[libserialport.download]]
    sha256 = "01dd8be4b3e494abde4f28addac281d1bfbf22023bb9ebb9cf5c6708200f8dd4"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.x86_64-w64-mingw32.tar.gz"
[[libserialport]]
arch = "aarch64"
git-tree-sha1 = "3ce3cb89e75276e2623d2fe6170813e302ea3a73"
libc = "musl"
os = "linux"

    [[libserialport.download]]
    sha256 = "3453964eee0fb4b92660b98d608dbf4a115e5309f0b789be7a606b25af1f7932"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.aarch64-linux-musl.tar.gz"
[[libserialport]]
arch = "i686"
git-tree-sha1 = "505907b9d6e80e33f0c51d724e9c6623301e1e0f"
libc = "glibc"
os = "linux"

    [[libserialport.download]]
    sha256 = "80b3bedc36fd3d1afaded21f649b2ddfac346ee1b9b83cddaf29783b92ced5c2"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.i686-linux-gnu.tar.gz"
[[libserialport]]
arch = "x86_64"
git-tree-sha1 = "f2dd3ae282a128b1ab8ae0de9a9a428c3d5375df"
libc = "musl"
os = "linux"

    [[libserialport.download]]
    sha256 = "a6514616cb3ef3bd790ec911ba322332e426ecef610002d3344242cf047b5a68"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.x86_64-linux-musl.tar.gz"
[[libserialport]]
arch = "i686"
git-tree-sha1 = "5a8991b1733d027f4fe39f402356e81423ca3e81"
os = "windows"

    [[libserialport.download]]
    sha256 = "1280e51553ab61e4919daccb7ecab29eeacf31027bc5510e256b7ed34bf1853c"
    url = "https://github.com/JuliaBinaryWrappers/libserialport_jll.jl/releases/download/libserialport-v0.1.1+1/libserialport.v0.1.1.i686-w64-mingw32.tar.gz"
